Revert "FGJ-36 set sensible defaults for grpc"
This reverts commit eef82e29ed11b2028201a3f5576ae3e4a99b22f9.

Reason for revert: This change introduced failures in integrations tests related to NetworkConfigTest.testLoadFromConfigFileYamlNOOverrides:304 expected:<2> but was:<120000>

Change-Id: I634def8fb8a20fb35f36c032661f9e900b19407e
Signed-off-by: Brett Logan <Brett.T.Logan@ibm.com>